name: Cypress Testing
run-name: ${{github.actor}} run TestSuite in ${{github.ref_name}}
on:
    push:
        branches-ignore: [main]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 20.12.2
            
            - name: Installing Dependencias
              run:
                  npm ci
                  npm list


            - name: cypress Run test coverage in chrome
              uses: cypress-io/github-action@v4
              with:
                  browser: chrome
                  command:
                    npm run file "ubicacbion del testSuite"
            - name: artefacto mochawesome HTML report
              if: always()
              uses: actions/upload-artifact@v3
              with:
                    name: test-report
                    path:
                      mochawesome-report
                      result